### ISSUE TITLE
issue with empty start row

### ISSUE THREAD

**Issue by iphony** [dilshod/xlsx2csv#10]
Hi,

The parser seems to turn into troubles with xlsx files with empty row 1.
It returns:

> > ...
> > self.colNum = cellId[:len(cellId)-len(self.rowNum)]
> > TypeError: object of type 'NoneType' has no len()

Without success, I tried to fix it by "ignoring" the cell with NoneType and go on with empty value, but this makes the data in following rows to be missing in the CSV output.

It only happens if the input XLSX has an entirely empty row 1.

Do you have an idea how to deal with this issue?

Thanks for help and thanks for the great .py!

**Comment by shashankchourasia2012** [comment]
Getting TypeError while converting xls to csv

![image](https://user-images.githubusercontent.com/4589525/37464648-0183a67a-287f-11e8-840f-85fe8b139817.png)

![image](https://user-images.githubusercontent.com/4589525/37464676-13318f4a-287f-11e8-94eb-32624298e114.png)

Please help with this
