### ISSUE TITLE
French character conversion issue

### ISSUE THREAD

**Issue by prabhatgouda** [dilshod/xlsx2csv#105]
French character conversion not proper . please help . Trying to use -c OUTPUTENCODING with WE8ISO8859P1 encoding format not able to do so . Need help .

**Comment by prabhatgouda** [comment]
Need someone's help here

**Comment by prabhatgouda** [comment]
can anyone look into this please

**Comment by dilshod** [comment]
can you send sample xlsx file?

**Comment by prabhatgouda** [comment]
[sample.xlsx](https://github.com/dilshod/xlsx2csv/files/360833/sample.xlsx)
please find attached sample.xlsx file ,which should be converted to sample.csv with exactly same French characters . which is not happening .. please provide me the xlsx2csv command line call options to do so .
currently we are using below versions .
xlsx2csv :  __version__ = "0.7.2"
python  : python2.6

**Comment by dilshod** [comment]
i don't know what it should look like, but for me cvs output is same as a preview

<img width="354" alt="screen shot 2016-07-13 at 13 43 56" src="https://cloud.githubusercontent.com/assets/14001/16797223/f39c9946-48ff-11e6-9af1-5d04071b087b.png">

**Comment by prabhatgouda** [comment]
can you please provide me command line call for xlsx2csv that you use... I use like below
 shell prompt> xlsx2csv  ./sample.xlsx ./sample.csv

**Comment by dilshod** [comment]
$ ./xlsx2csv.py ~/Downloads/sample.xlsx sample.csv
$ cat sample.csv 
Name
"SAINT,JÿRÿME"
"cr , crédit"
télé
récept
bas¿ 
 Movies abonnés

What is your output?

**Comment by prabhatgouda** [comment]
for me the output looks like below
$ ./xlsx2csv.py ./sample.xlsx ./sample.csv
$ cat sample.csv 
"SAINT,JÃ¿RÃ¿ME"
"cr , crÃ©dit"
tÃ©lÃ©
rÃ©cept
basÂ¿
 Movies abonnÃ©s

**Comment by dilshod** [comment]
Try to convert it to different encodings:

iconv -f UTF-8 -t WINDOWS-1252 sample.csv > sample-win1252.csv

or

iconv -f UTF-8 -t UTF-16LE sample.csv > sample-16le.csv

**Comment by dilshod** [comment]
What operating system are you using? Your terminal's encoding is not utf-8. Try to open csv file using excel application.

**Comment by prabhatgouda** [comment]
Linux 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
I use above .. tried with iconv . does not work

**Comment by prabhatgouda** [comment]
Can you please advise me , how can I resolve this issue using option xlsx2csv  -c OUTPUTENCODING WE8ISO8859P1 ./sample.xlsx ./sample.csv . please provide me correct syntax for command line . it does not work for me .

**Comment by dilshod** [comment]
"-c" options is for python3 only. It has no effect on python 2.6.
Try to convert utf-8 to ISO-8859-1 using command:

iconv -f UTF-8 -t ISO-8859-1 ~/Downloads/sample.csv > ~/Downloads/sample-8859-1.csv

or

xlsx2csv.py ~/Downloads/sample.xlsx | iconv -f UTF-8 -t ISO-8859-1 > ~/Downloads/sample.csv
