### ISSUE TITLE
VALUE("+0") doesn't evaluate to zero

### ISSUE THREAD

**Issue by jhfrontz** [dilshod/xlsx2csv#118]
I'm importing from xlsx files generated in a microsoft environment while running in a MacOS (10.11.6) environment.  In the original environment (and in OpenOffice on MacOS), VALUE("+0") evaluates to zero.  However, when parsing using xlsx2csv (version 0.7.2), the result is non-numeric.

**Comment by setop** [comment]
`=VALUE("+0")` does not evaluate to zero in msexcel 2007 (v12.0) ; it evaluates to "#NAME".

When LibreOffice.calc save this to a .xlsx file, it is converted to `=CNUM("+0")` which evaluates to zero in msexcel 2007.

can you provide a minimal sample document ?

**Comment by jhfrontz** [comment]
Here's an example: [minimal4github.xlsx](https://github.com/dilshod/xlsx2csv/files/944319/minimal4github.xlsx)

- LibreOffice 5.1.0.3 and OpenOffice 4.1.3 evaluate columns 3 and 4 of row 1 as 0.
- xlsx2csv shows them as empty.
- MacOS Numbers 3.6.2 shows them as errors (_VALUE requires a string specifying a number, but found “+0” instead._)

I don't have a native microsoft environment to try this in (the files I'm converting all originate there -- which I'm assuming is using the latest version of Word for windows, whatever that might be).



I don't completely understand the xlsx format, but it's almost like there is a pre-calculated result stored with a formula?  I get differing results when importing this file to google docs.

**Comment by setop** [comment]
`=VALUE("+0")` does not evaluate to zero in msexcel 2007 (v12.0) ; it evaluates to "#NAME".

When LibreOffice.calc save this to a .xlsx file, it is converted to `=CNUM("+0")` which evaluates to zero in msexcel 2007.

can you provide a minimal sample document ?

**Comment by setop** [comment]
Indeed the file you created make xlsx2csv to produce empty value.

I tried LO 5.1.6.2 and LO 5.3.0.3 to save as xlsx file and then xlsx2csv produce 0.

There is a difference between the file generated by  LO 5.1.0.3 and LO 5.1.6.2. The later adds a v xml element (v for value) element along with the f xml element (f for formula). xlsx2csv use this v xml element to output csv ; same as msexcel does. xlsx2csv is not supposed to perform formula evaluation.

I would say the bug is on LO side. You should try to upgrade.

**Comment by jhfrontz** [comment]
> I would say the bug is on LO side. You should try to upgrade.

As I mentioned in the OP, the original files in question were generated by microsoft Excel in a microsoft environment (the example file was generated on MacOS).


>  The later adds a v xml element (v for value) element along with the f xml element (f for formula). xlsx2csv use this v xml element to output csv ; same as msexcel does. xlsx2csv is not supposed to perform formula evaluation.

OK, I think this must be the root cause -- I was mistakenly thinking that xlsx2csv did some sort of evaluation (even though I couldn't see where that was happening (e.g., maybe the XML-manipulation packages had some magic that I wasn't grasping). It sounds like I should find out how the upstream files are being generated (e.g., they might be exported/generated prior to actually "executing" the formulas and thus there is no value/result to store in the file?).

**Comment by setop** [comment]
I open the example file you provide with msexcel under mswindows and save it back.
The v XML elements are now present.
I think the msexcel version which as been used does not behave like msexcel 2007 under mswindows.
I don't know if these elements are mandatory. At least they are useful.

**Comment by jhfrontz** [comment]
OK, thanks for the clarification.  I'll close this since it is an issue with the document creator.

**Comment by setop** [comment]
By the way, it could be a valid request to ask for an option which allow to put the formula instead of the value in the CSV.
