### ISSUE TITLE
fails on large xlsx files

### ISSUE THREAD

**Issue by Alexdr** [dilshod/xlsx2csv#12]
I am trying to convert some large xlsx files in the range of 60,000 to 85,000 lines.
The program fails with the error:

$ xlsx2csv.py -s 1 60656.xlsx 60656.csv
Traceback (most recent call last):
  File "/home/Alex/mybin/xlsx2csv.py", line 412, in <module>
    xlsx2csv(args[0], outfile, **kwargs)
  File "/home/Alex/mybin/xlsx2csv.py", line 98, in xlsx2csv
    workbook = parse(ziphandle, Workbook, "xl/workbook.xml")
  File "/home/Alex/mybin/xlsx2csv.py", line 125, in parse
    instance.parse(ziphandle.read(filename))
  File "/home/Alex/mybin/xlsx2csv.py", line 135, in parse
    self.appName = workbookDoc.firstChild.getElementsByTagName("fileVersion")[0]._attrs['appName'].value
IndexError: list index out of range

I am using python 2.7 under linux.
I have tested the script with other xlsx files (smaller) and had no issus.

Thanks
Alex.

**Comment by upicik** [comment]
Hi @dilshod , I am receiving the same error even though files are not that big - Xlsx2csv instance has no attribute 'zaiphandle' in <bound method ...>
the worksheet.xl  contains: 
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?> 
- <workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <fileVersion appName="xl" lastEdited="4" lowestEdited="4" rupBuild="4505" /> 
  <workbookPr filterPrivacy="1" defaultThemeVersion="124226" /> 
- <bookViews>
  <workbookView xWindow="240" yWindow="105" windowWidth="14805" windowHeight="8010" /> 
  </bookViews>
- <sheets>
  <sheet name="Sheet1" sheetId="1" r:id="rId1" /> 
  </sheets>
- <definedNames>
  <definedName name="page\x2dtotal">Sheet1!$A$13755</definedName> 
  <definedName name="page\x2dtotal\x2dmaster0">Sheet1!$A$13755</definedName> 
  </definedNames>
  <calcPr calcId="124519" /> 
  </workbook>
I will be working with excel files not created by machiene, will it be problematic in the future?

**Comment by vingally** [comment]
Hi Dilshod, 

I am getting the below error when i execute the code.

xlsx2csv test_1.xlsx test_1.csv

Exception AttributeError: "Xlsx2csv instance has no attribute 'ziphandle'" in <bound method Xlsx2csv.__del__ of <__main__.Xlsx2csv instance at 0x7fc8c1fd40e0>> ignored

**Comment by dilshod** [comment]
vingally,
i need to try it myself, can you email me your file?

**Comment by exedor** [comment]
I'm getting this same error, but it's really strange. I only see it when I run xlsx2csv from go via systemd on fedora 25. I've tried it under CentOS and it works great all the time. There is a minor python version difference but I don't think that's the problem because it always works at the command line.
