### ISSUE TITLE
—skipemptycolumns option not working.

### ISSUE THREAD

**Issue by ufrese** [dilshod/xlsx2csv#125]
The line

   parser.add_argument("--skipemptycolumns", dest="skip_trailing_columns", default=False, action="store_false",
     help="skip trailing empty columns")

should be

… „store_true“…

**Comment by dilshod** [comment]
changed to store_true, thanks

**Comment by ankur334** [comment]
I am not able to skip the empty columns when trying to convert xlsx to csv. @ufrese @dilshod Any from your side will be a great help for me.

**Comment by turicas** [comment]
@ankur334 could you please provide more details, like a sample file and the full command-line you've run?

**Comment by ankur334** [comment]
@turicas is it possible to convert XLSX to CSV and skip all those empty columns? I am  attaching one of the sample files
[Sample_file.xlsx](https://github.com/dilshod/xlsx2csv/files/4306652/Sample_file.xlsx)  
Can I pass some arguments while running `Xlxs2csv()` command?
