### ISSUE TITLE
Default outputencoding option not set

### ISSUE THREAD

**Issue by Hasan-J** [dilshod/xlsx2csv#135]
Hey, I've just noticed that when first initializing the object Xlsx2csv there is no line setting the default encoding option as **utf-8** , so I've added this line:
`options.setdefault("outputencoding",` "utf-8")

Maybe If I'm not mistaken I could issue a pull request for you to integrate this update.
Thanks for this clean work.

**Comment by james1293** [comment]
I ran into this problem also. @Hasan-J , did you do a PR?

**Comment by Hasan-J** [comment]
Hi @james1293 , you can check this PR #178 .
If not merged, then clone my fork maybe.
