### ISSUE TITLE
Keeping leading Zero/s

### ISSUE THREAD

**Issue by Sartoric** [dilshod/xlsx2csv#139]
Hi 
This is more a question than an actual issue (well, it is an issue for me 😄 )
Is there any way to keep the leading zero for text/number columns or any way to specify to export all as text ? 
If there are values like 02 (in fact text) they are exported as 2 (number)

eg. 
I should use that value for data mapping on multiple columns (concatenated) 
So I could have 2 columns |02|02| 
and mapping 0202 is not the same as mapping 22

Tnx

**Comment by Sartoric** [comment]
No one has ever faced this problem ?

**Comment by dilshod** [comment]
I can take a look if you send xlsx file

**Comment by Sartoric** [comment]
Sure, let me check if I can send you a sample.

Thank you

**Comment by Sartoric** [comment]
@dilshod 
Here it is.

I was trying to send you a "1 row sample" and I've noticed that the new file was correctly converted. 
If I just open the source file (using excel or libreoffice) and save it, the conversion works as expected.
Unfortunately I can't do it.

[test.xlsx](https://github.com/dilshod/xlsx2csv/files/1819508/test.xlsx)

**Comment by dilshod** [comment]
I've made changes, give it a try

**Comment by Sartoric** [comment]
works like a charm :thumbsup:

Thanks
