### ISSUE TITLE
Digits lost in conversion

### ISSUE THREAD

**Issue by Sartoric** [dilshod/xlsx2csv#142]
Hi
I've just faced a strange issue. 
I have a price column with values that lost some digits during conversion (9 rows out of 15200).
eg. 
756 -> 6
178 -> 78

I didn't checked yet if the problem is related just to that column or not.

Sample attached
[test.xlsx](https://github.com/dilshod/xlsx2csv/files/1847097/test.xlsx)

**Comment by Sartoric** [comment]
Forgot one detail. 
If I open-save the file with Libreoffice it seems to work as expected.

**Comment by setop** [comment]
I'm conducting some tests.
Can you confirm that cell G18 is "SH" in csv but should be "BOSH" as found in xlsx ?

**Comment by Sartoric** [comment]
Hi @setop 
Yes, values should be the same as found in xlsx.
I can't confirm about that specific cell as I've deleted the converted file.

**Comment by setop** [comment]
Issue fixed and merged.
Should be closed.

**Comment by Sartoric** [comment]
Looks fine now. Thanks.
