### ISSUE TITLE
Inconsistent free software license.

### ISSUE THREAD

**Issue by kfogel** [dilshod/xlsx2csv#147]
Thanks for this very useful program.  There is some licensing confusion in the repository:

1. `COPYING` contains the GNU Library General Public License (LGPL-2.0, which is nowadays called the "GNU Lesser General Public License" by the FSF, and for which there are later versions available btw)

2. `LICENSE.txt` contains the GNU GPL-3.0, which is a very different license from the LGPL-2.0

Then the `README` says something that is consistent with neither of the above:

> All programs in this directory and subdirectories are published under license GNU GPL version 2 or (at your option) any later version. For more information, see COPYING or visit <http://www.gnu.org/copyleft/gpl.html>.

Neither of the two licenses supplied is the GPL-2.0, and specifically the license in `COPYING` is not any version of the GPL -- it is the LGPL instead.

The copyright header in `xlsx2csv.py` is consistent with what the `README` file says:

> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

What license would you like the program to be under?  (I'm happy to supply a pull request to make it convenient, by the way, but would need to know your intended license in order to do it.)

**Comment by ariel11** [comment]
Hi,

Can you clarify what the COPYING file (GNU LIBRARY GENERAL PUBLIC LICENSE, Version 2) covers?  

Is the overall project license GPL-2.0-or-later where people can choose either GPL-2.0 or GPL-3.0 (the LICENSE.txt)?

Thanks

**Comment by kfogel** [comment]
I'm not sure how @dilshod has notifications set up, so nick-flagging here just in case.

**Comment by dilshod** [comment]
Hi,

Which license do you prefer? or can you make a pull request?

**Comment by ariel11** [comment]
@dilshod - thank you.  I don't really have a license preference.  Mainly want to clarify the license for our use.  It seems to me like the intended project license has been "GPL-2.0-or-later."  If that is the license you intended to apply, then I think we'd remove the LICENSE.txt (GPL-3.0) and COPYING (LGPL-2.0) files and replace them with a new COPYING file that just has the GPL-2.0 text.  This would then be consistent with the copyright header and section of the README that @kfogel pointed to above.

**Comment by capfei** [comment]
@dilshod I submitted #210 to update the license info to GPL 2.0. You didn't state a preferred license so I went with what is listed the most in the repo. If you want a different license, feel free to close the PR.
