### ISSUE TITLE
KeyError in `getSheetIdByName` (since 0.7.5)

### ISSUE THREAD

**Issue by klamann** [dilshod/xlsx2csv#172]
The naming in `Xlsx2csv.workbook.sheets` has changed from `[{'name': 'foo', 'id': 42}]` to `[{'name': 'foo', 'index': 42}]`, but in `Xlsx2csv.getSheetIdByName`, `id` is still used instead of `index`. This causes a KeyError.

Also, this caused my code to break, since I didn't expect any breaking changes from a minor release like this. Maybe change it back to `id` and switch to `index` in 0.8.0?

**Comment by dilshod** [comment]
I tried to fix it, please give it a try

**Comment by klamann** [comment]
Thanks for the update. I suppose you mean commit 173edbc8c318b2e54a15b8641ef6cf621a07e904?

There are two issues with it:

1. `dict.has_key` is not available in Python 3 (use the `in` keyword instead, e.g. `'foo' in dict`)
2. the checks for `index` with a fallback to `id` should not be necessary, when `index` is used everywhere instead of `id`.

It would probably be sufficient to get rid of the checks and just change the [return value](https://github.com/dilshod/xlsx2csv/blob/173edbc8c318b2e54a15b8641ef6cf621a07e904/xlsx2csv.py#L210) to `s['index']`

**Comment by dilshod** [comment]
oh, I got it now, someone renamed it from id to index, but he did not rename it everywhere

**Comment by dilshod** [comment]
if I just duplicate the "index" property and call it "id", and republish it as 0.7.5 version, will it solve your problem? On 0.8.0 I'll remove it, probably

**Comment by klamann** [comment]
> oh, I got it now, someone renamed it from id to index, but he did not rename it everywhere

yes, that's the problem

> if I just duplicate the "index" property and call it "id", and republish it as 0.7.5 version, will it solve your problem?

Yeah, I guess that should work. I'm not a friend of overwriting releases, maybe just go to 0.7.6 and add a note in the changelog that there was a bug in the previous release?

**Comment by dilshod** [comment]
Done

**Comment by klamann** [comment]
Works like a charm, thanks for solving this :)
