### ISSUE TITLE
CSV File Size double Excel file

### ISSUE THREAD

**Issue by Zekepao** [dilshod/xlsx2csv#184]
Hello, For some reason the CSV file created is double the size (or more) of the original excel file. Is there a way to make the file lighter? 

The original files have only one sheet with several columns (less than 30). One of the is for date and time and the others have float numbers. The files are usually around 100MB in size. The targe files are created with just one line of code (below) and the output is over 180MB in all cases. I would expect csv to trim a lot of the excel garbage but not sure what I'm doing wrong.

Xlsx2csv(name, outputencoding="utf-8").convert(os.path.splitext(name)[0]+".csv")

Is it a problem with not specifying format for each column? and if that is the case, could you provide an example on how to do it because I don't really understand how formats are defined in this line of command.

Thanks for your help. Really appreciated.

**Comment by turicas** [comment]
The XLSX format is a zipped archive, it means even if it stores more data, all the data is therefore compressed and then the final size would be smaller than non-compressed CSV. If you compress the generated CSV using zip or gzip compression method you'll probably get a smaller file. You can use this simple function to compress the file lazily:

```python
import gzip

def compress(filename, output_filename, chunk_size=1024 ** 2):
    with open(filename, mode="rb") as fobj:
        output = gzip.GzipFile(output_filename, mode="wb")
        data = fobj.read(chunk_size)
        while data:
            output.write(data)
            data = fobj.read(chunk_size)
            
compress(name, name + ".gz")
```

Note: it would be awesome if xlsx2csv accepts compressed filenames, so it compresses the output file automatically depending on the extension. I've done something like this in [rows project](https://github.com/turicas/rows) ([check this function](https://github.com/turicas/rows/blob/develop/rows/utils.py#L527)) and could create a PR if it's desirable. What do you think, @dilshod?

**Comment by Zekepao** [comment]
Thank you for the answer @turicas ! It does makes sense.

Cheers!
