### ISSUE TITLE
Feature request: write CSV to stdout

### ISSUE THREAD

**Issue by shindere** [dilshod/xlsx2csv#213]
Many thanks for the helpful tool!

At the moment

```bash
xlsx2csv foo.xlsx -
```

creates a file named "-" and

```bash
xlsx2csv foo.xlsx /def/sdtout
```

produces the following error:

```python
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 1129, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/bin/xlsx2csv", line 216, in convert
    self._convert(sheetid, outfile)
  File "/usr/bin/xlsx2csv", line 266, in _convert
    outfile = open(outfile, 'w+', encoding=self.options['outputencoding'], newline="")
io.UnsupportedOperation: File or stream is not seekable.
```

(The smae holds for `/dev/fd/1`.)

Could the tool be extended so as to support writing the CSV file
to its standard output, please?

In the same vein it may be nice to be able to read the XLSX content
from stdin so that the tool can be fully integrated in a pipe, if
that is not yet supported.

**Comment by dilshod** [comment]
Try just
`xlsx2csv foo.xlsx`
it will write csv to stdout

**Comment by shindere** [comment]
Dilshod Temirkhodjaev (2020/12/28 04:05 -0800):
> Try just
> `xlsx2csv foo.xlsx`
> it will write csv to stdout

Oh! So sorry I dind't try that!

Feel free to close the issue!
