### ISSUE TITLE
xlsx2csv does not raise exceptions for fatal errors, which makes it hard to use as a library.

### ISSUE THREAD

**Issue by ghuls** [dilshod/xlsx2csv#233]
xlsx2csv does not raise exceptions for fatal errors, which makes it hard to use as a library.

There are several instances where `eprint()` followed by sys.exit(1) or `return 1` are used.
https://github.com/dilshod/xlsx2csv/blob/de96b659b7ce531d08246b912fa654a4ded62629/xlsx2csv.py#L131-L132

To have it kind of working as a library, I have to overwrite `eprint` with my own function that raises an exception:
https://github.com/pola-rs/polars/pull/3567/commits/65464c225762d7c92c7e7f3aa8920974a3b3329a#diff-5f0fd72b20838297a2173cfaafc9b6b1348b05eb43f1a47ee3d6f4c8cf73abe6R1087-R1092

It would be great if it would be properly handled in xlsx2csv so polars can support reading Excel files without this hack: https://github.com/pola-rs/polars/pull/3567

**Comment by cnpryer** [comment]
I feel like this is just moving a hack, but if you want this i can submit the PR. https://github.com/dilshod/xlsx2csv/compare/master...cnpryer:improve-eprint

**Comment by dilshod** [comment]
I like the idea of raising an exception, can you create a pull request?

**Comment by cnpryer** [comment]
@ghuls wdyt of #235?
