### ISSUE TITLE
Will there be a new release?

### ISSUE THREAD

**Issue by cnpryer** [dilshod/xlsx2csv#236]
Recently we made some error handling improvements here (#235). Will this be released in a new version at some point?

**Comment by cnpryer** [comment]
Also I noticed `master` is at `0.8` but PyPi is [`0.7.8`](https://pypi.org/project/xlsx2csv/). Should I anticipate a 0.7.9, 0.8.0, or a 0.8.1 for the change referenced?

**Comment by dilshod** [comment]
Sorry. I uploaded 0.8.0 release.

**Comment by cnpryer** [comment]
Awesome! Thanks!
