### ISSUE TITLE
Github release out of sync: showing latest as 0.7.8, instead of correct 0.8.1

### ISSUE THREAD

**Issue by corneliusroemer** [dilshod/xlsx2csv#255]
The Github release is not up to date:

![image](https://user-images.githubusercontent.com/25161793/225076110-16e3cabb-4a94-49b9-ac37-53ac5acd9e2d.png)

Latest release seems to be 0.8.1, but Github release shows 0.7.8 as latest.

**Comment by dilshod** [comment]
Created 0.8.1 release. Thank you
