### ISSUE TITLE
Feature request: read xlsx from STDIN

### ISSUE THREAD

**Issue by ferdinandyb** [dilshod/xlsx2csv#263]
I'd love to use something like this in [aerc filters](https://git.sr.ht/~rjarry/aerc), but as far as I can tell, the file to convert must already be on the disk, while I need to be able to pipe it into `xlsx2csv`.

**Comment by alephreish** [comment]
It works: `in | xlsx2csv /dev/stdin | out` (using version `0.8.1`)

**Comment by ferdinandyb** [comment]
I tried it but I get:

```
Invalid xlsx file: /dev/stdin
Exception ignored in: <function Xlsx2csv.__del__ at 0x7f41ae498b80>
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 213, in __del__
AttributeError: 'Xlsx2csv' object has no attribute 'ziphandle'
```

both the aerc filter and `cat example.xlsx | xlsx2csv /dev/stdin` produces the same problem.

**Comment by alephreish** [comment]
Oh, sorry, apparently I forgot to post an update to my comment: I've been playing with `xlsx2csv /dev/stdin < example.xlsx` which does work but for `cat example.xlsx | xlsx2csv /dev/stdin` it return the above exception.

**Comment by ferdinandyb** [comment]
I've made a python3 only PR. I imagine it could be updated to include python2 as well.
