### ISSUE TITLE
Upload whl for 0.8.2?

### ISSUE THREAD

**Issue by MasterOdin** [dilshod/xlsx2csv#276]
Would it be possible to upload a whl for the `0.8.2` release? We looked to upgrade `xlsx2csv` on our ubuntu-22.04 system, but are running into issues as it uses pip 22.0.2 (from `python3-pip`) and trying to install from source throws an error:

```
    ubuntu-22.04: Collecting xlsx2csv==0.8.2
    ubuntu-22.04:   Downloading xlsx2csv-0.8.2.tar.gz (227 kB)
    ubuntu-22.04:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 KB 18.4 MB/s eta 0:00:00
    ubuntu-22.04:   Installing build dependencies: started
    ubuntu-22.04:   Installing build dependencies: finished with status 'done'
    ubuntu-22.04:   Getting requirements to build wheel: started
    ubuntu-22.04:   Getting requirements to build wheel: finished with status 'done'
    ubuntu-22.04:   Preparing metadata (pyproject.toml): started
    ubuntu-22.04:   Preparing metadata (pyproject.toml): finished with status 'done'
    ubuntu-22.04:   WARNING: Generating metadata for package xlsx2csv produced metadata for project name unknown. Fix your #egg=xlsx2csv fragments.
    ubuntu-22.04: Discarding https://files.pythonhosted.org/packages/c9/d1/70613896bd07a49cfb19312838b8ffb29232e6be5c8e381b953473468e5b/xlsx2csv-0.8.2.tar.gz#sha256=cdd272c82f8b32f1cee76aeaef87b2ee3549661fddf90f7ecf2310967a16fc84 (from https://pypi.org/simple/xlsx2csv/): Requested unknown from https://files.pythonhosted.org/packages/c9/d1/70613896bd07a49cfb19312838b8ffb29232e6be5c8e381b953473468e5b/xlsx2csv-0.8.2.tar.gz#sha256=cdd272c82f8b32f1cee76aeaef87b2ee3549661fddf90f7ecf2310967a16fc84 (from -r /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/pip/system_requirements.txt (line 25)) has inconsistent name: filename has 'xlsx2csv', but metadata has 'unknown'
    ubuntu-22.04: ERROR: Could not find a version that satisfies the requirement xlsx2csv==0.8.2 (from versions: 0.6, 0.6.1, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.8.1, 0.8.2)
    ubuntu-22.04: ERROR: No matching distribution found for xlsx2csv==0.8.2
```

This seems like an issue with pip that was fixed in a later version, but we can't upgrade it, and so would love to see a `whl` provided as has been for prior versions, which would avoid this issue altogether.

**Comment by Konfekt** [comment]
Might it be [because the git repo is still stuck at 0.8.1](https://github.com/dilshod/xlsx2csv/commit/f2a429a3307d866927b58a58e40c6c5e157e80d5#comments) ?

**Comment by DeflateAwning** [comment]
Would appreciate this getting dealt with!

**Comment by dilshod** [comment]
Created a new release here with whl https://github.com/dilshod/xlsx2csv/releases

**Comment by DeflateAwning** [comment]
Thanks a lot! Perhaps you may want to setup a build pipeline to automatically tag and publish releases. 

I always appreciate when version control tags align with PyPi/package manager releases; makes auditing and reviewing much easier.

I think this issue can be closed now?

**Comment by MasterOdin** [comment]
The whl file was not uploaded to https://pypi.org/project/xlsx2csv/0.8.2/#files, so the same issue for me remains, where trying to install `xlsx2csv==0.8.2` would continue to fail

**Comment by MasterOdin** [comment]
I see it's uploaded now, thanks @dilshod!
