### ISSUE TITLE
Please add tag "release/N.N.N" in the future

### ISSUE THREAD

**Issue by jaalto** [dilshod/xlsx2csv#33]
Hi,

It would nice if the repository were tagged on release in order to (1) diff between releases (2) use automated tools to package releases in regular basis (http://githubredir.debian.net/). 

Use of "<b>release/</b>" prefix helps to find tags by name easily with <code>git tag -l</code>:

```
release/1.0
release/1.1
release/1.10
release/1.2
```

**Comment by turicas** [comment]
Hi, @jaalto. Sorry for ressurecting this issue. There are some tags on the repository already:

```bash
$ git tag -l
0.7.3
0.7.4
0.7.5
0.7.6
release/0.5
release/0.6
release/0.7
```

So I'm closing this issue.
