### ISSUE TITLE
Date formatting issue (v0.14)

### ISSUE THREAD

**Issue by paklein** [dilshod/xlsx2csv#6]
An xlsx file I'm processing contains a date cell that looks like "9/15/2011 15:22" in Excel. I haven't been able to figure out what format to pass to xlsx2csv in order to resolve this.
(1) [no format passed]: m/15/11 h:09
(2) %Y/%m/%d %hh:%mm : 2011/09/15 Seph:09m
(3) %Y/%m/%d %H:%M : 2011/09/15 00:00

The last seem closest, but I would like to see the hours:minutes resolved.

**Comment by Hzefeng** [comment]
Sorry, could you help me please
`for /f "delims=" %%i in ('dir /b /a-d /s "*.xlsx"') do (xlsx2csv.py -f %Y/%m/%d %H:%M -s 1  %%i %%iout.csv)`
the result shows
`xlsx2csv.py: error: too few arguments`
what's wrong with the code?
thank you so much
