### ISSUE TITLE
x: namespace

### ISSUE THREAD

**Issue by MichalHaltuf** [dilshod/xlsx2csv#68]
I need to convert XLSX file, where a strange "x:" namespace is used in XML markup (element x:workbook instead workbook etc.), but XLSX2CSV fails to do it.

Many parsers fail to open such file, so I'm wondering if the file is somehow corrupted... But MS Excel opens it without any problem, and when I manually remove the x: namespace from markup, XLSX2CSV is able to read it.

Is there any way to make XLSX2CSV work on such file without having to manually edit the source XML markup and removing the x: namespace? I'm able to send the problematic file in case it's needed.

**Comment by davidcollins** [comment]
A few people have found my lightweight procedural script useful for converting [XLSX to CSV](http://davidacollins.com/weblog/xlsx2csv) 

http://davidacollins.com/weblog/xlsx2csv
https://github.com/davidcollins/xlsx2csv

There are a few more recent additions to the XLSX-to-CSV solution by other developers  here on GitHub.

**Comment by dilshod** [comment]
can you send a sample file?

**Comment by MichalHaltuf** [comment]
http://michal.imagineo.cz/MonthlyOverview.xlsx

**Comment by dilshod** [comment]
it should be fixed

**Comment by MichalHaltuf** [comment]
excelent, thanks!
