### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by labe-me** [dilshod/xlsx2csv#70]
Hello,

I experienced an error running the script on an uff-8 file with italian characters.

I fixed the problem replacing (at line 347):

    "target" : target and str(target.value) or None

with 

    "target" : target and str(target.value.encode("utf-8")) or None

It's a quick and dirty hack which worked for me but you may want to look into the problem and do something cleaner :)

Best regards and thank you for all the fish.

**Comment by dilshod** [comment]
thanks
