### ISSUE TITLE
PyPI package out of date - contains typo: options.setdefault("delimeter", ",")

### ISSUE THREAD

**Issue by SimKennedy** [dilshod/xlsx2csv#71]
I have just installed xlsx2csv using pip and there is this typo that is not in the github version despite the same version number. I guess PyPI just needs updating.

"delimeter" should be "delimiter" in xlsx2csv.py

def __init__(self, xlsxfile, **options):
        # dateformat=None, delimiter=",", sheetdelimiter="--------", skip_empty_lines=False, escape_strings=False, cmd=False
        options.setdefault("delimeter", ",")
        options.setdefault("sheetdelimiter", "--------")
        options.setdefault("skip_empty_lines", False)

**Comment by dilshod** [comment]
uploaded to pypi 0.7.2 version
