### ISSUE TITLE
Should timestamps be rounded?

### ISSUE THREAD

**Issue by duncan-bayne** [dilshod/xlsx2csv#84]
I have a spreadsheet that contains two timestamps that are rendered as being midnight:

![screenshot from 2015-09-04 09 16 49](https://cloud.githubusercontent.com/assets/65949/9673669/1abed3de-52ea-11e5-800d-227a2b96e491.png)

However when I extract them, one is exported as 23:59:59:

```
➜  tmp  xlsx2csv test.xlsx
05/10/2013 00:00:00
04/10/2013 23:59:59
```

The underlying problem seems to be a lack of rounding when extracting.  Here's the actual XML:

```
  <sheetData>
    <row r="1" customFormat="false" ht="12.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false">
      <c r="A1" s="1" t="n">
        <v>41552</v>
      </c>
    </row>
    <row r="2" customFormat="false" ht="12.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false">
      <c r="A2" s="1" t="n">
        <v>41551.9999999998</v>
      </c>
    </row>
  </sheetData>
```

Should xlsx2csv be rounding these values before exporting?  It's confusing to have one value displayed in the spreadsheet, but a different value exported to CSV.

**Comment by guzzijones** [comment]
I would agree that there is some rounding going on to x*10 ^ -9.  
I suppose we could search on the microsoft website for the precision details of the date value number they use.
maybe the first three decimals is hours, next three decimals is minutes, and the next three are seconds.
If we round 41551.9999999998 to t0 ^-9 then we would get 41552.  which would then give you the correct date.
Does that seem right?

**Comment by guzzijones** [comment]
could you post your spread sheet somehow?

**Comment by duncan-bayne** [comment]
I've uploaded it [here](http://live25percentlonger.com/rounding.xlsx).

**Comment by duncan-bayne** [comment]
A friend of mine is quite knowledgeable about Excel internals; I've asked him for comment.  I'm not sure what the right behaviour is, but I'm pretty sure it's not the not-rounded one.

**Comment by asadeghi** [comment]
The behavior as it stands could justifiably be correct because it is exporting the value stored in the cell directly to CSV. However it isn't consistent with the behavior of Excel when saving to CSV, or that of Excel when rendering the date/time in the grid. So it really depends on what the goal is. 
If you are trying to emulate Excel's own CSV export functionality (which attempts to give you exactly what you see in the grid) then you might be opening a rather big can of work that won't stop at floating-point precision issues.

**Comment by duncan-bayne** [comment]
Closing this after ~ 8 years inactivity.
