### ISSUE TITLE
Support for seconds in time

### ISSUE THREAD

**Issue by lepennec** [dilshod/xlsx2csv#99]
Thank you for your very valuable tool.
I've discovered that the time is rounded to the closest minute line 623 even if it is stored with more precision in the excel file. I wonder if a flag similar to dateformat could be use to specify the timeformat...
Erwan

**Comment by kousho** [comment]
Use `-t` or `--timeformat` option.
https://github.com/dilshod/xlsx2csv/blob/master/xlsx2csv.py#L1015-L1016

**Comment by lepennec** [comment]
Thank you for the update. This is indeed possible since 2017!
